### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by Pyjong** [olistic/warriorjs#105]
Hi,
I am sorry if this is something simple, but I really have tried. I am running the thing from Windows Bash. The install line works fine (with sudo). Running warriorjs however gives following output:

```
/usr/local/lib/node_modules/@warriorjs/cli/lib/cli.js:23
async function run(args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@warriorjs/cli/bin/warriorjs.js:3:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
What's wrong?

**Comment by olistic** [comment]
Hello @Pyjong! This is a duplicate of #80. Next time, please take the time to read and follow the issue template when submitting a new issue. WarriorJS requires Node >= 8 to work.

**Comment by Pyjong** [comment]
Right, thanks!
