### ISSUE TITLE
Error when running from home folder

### ISSUE THREAD

**Issue by AndreiBarsan** [olistic/warriorjs#11]
I invoked `warriorjs` from `~` on OSX Yosemite and it complained because I already had a `.profile` file.

```
Welcome to WarriorJS

/opt/some/folder/node_modules/warriorjs/lib/Profile.js:316
        throw new Error('Invalid .profile file. Try changing the directory und
              ^
Error: Invalid .profile file. Try changing the directory under you are running warriorjs.
    at Function.decode (/opt/some/folder/v0.10.38/lib/node_modules/warriorjs/lib/Profile.js:316:15)
    at Function.load (/opt/some/folder/nvm/v0.10.38/lib/node_modules/warriorjs/lib/Profile.js:322:57)
    at Game.start (...Game.js:56:46)
    at Runner.run (...Runner.js:42:18)
    at Object.<anonymous> (...warriorjs:6:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by Juburin** [comment]
Dublicate of #3 .
Also look at the error message "Try changing the directory under you are running warriorjs."
Says all, doesn't it :smile:

**Comment by olistic** [comment]
Will take the missing "which" into account. Thanks!
