### ISSUE TITLE
Error: ENOTDIR, not a directory

### ISSUE THREAD

**Issue by Sheraff** [olistic/warriorjs#4]
With a local install `Flo@Florians-MacBook-Pro-3:~/Desktop/warriorjs$ sudo npm install warriorjs` on node v0.10.33, I get the following error:

```
Flo@Florians-MacBook-Pro-3:~/Desktop/warriorjs/node_modules/warriorjs/bin$ ./warriorjs 
Welcome to WarriorJS

[1] beginner
[2] intermediate

Choose tower by typing the number: 1
Enter a name for your warrior: chap

/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/node_modules/fs-extra/lib/mkdir.js:87
          throw err0
                ^
Error: ENOTDIR, not a directory '/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/bin/warriorjs/chap-beginner'
    at Object.fs.mkdirSync (evalmachine.<anonymous>:653:18)
    at Object.mkdirsSync (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/node_modules/fs-extra/lib/mkdir.js:70:9)
    at PlayerGenerator.generate (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/lib/PlayerGenerator.js:52:32)
    at Level.generatePlayerFiles (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/lib/Level.js:161:46)
    at Game.prepareNextLevel (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/lib/Game.js:174:27)
    at Game.playNormalMode (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/lib/Game.js:117:16)
    at Game.start (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/lib/Game.js:70:14)
    at Runner.run (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/lib/Runner.js:42:18)
    at Object.<anonymous> (/Users/Flo/Desktop/warriorjs/node_modules/warriorjs/bin/warriorjs:6:8)
    at Module._coFlo@Florians-MacBook-Pro-3:~/Desktop/warriorjs/node_modules/warriorjs/bin$ 
```

**Comment by olistic** [comment]
The problem here is that the binary is called `warriorjs`, and the game is trying to create a `warriorjs/chap-beginner` directory in the same place the binary resides, making the `warriorjs` binary collide with the `warriorjs` directory being created.

If you want a local installation, launch the game like this:
```bash
$ ./warriorjs -d /path/to/another/directory
```
