### ISSUE TITLE
Problem in installing warriorjs

### ISSUE THREAD

**Issue by xeious** [olistic/warriorjs#79]
I tried to install warriorjs but I got this message: 

`npm WARN @warriorjs/tower-beginner@0.1.0 requires a peer of @warriorjs/core@^0.0.0 but none was installed.
`
And when I try to run it by writing warriorjs in my terminal I got this message:

`/usr/local/lib/node_modules/@warriorjs/cli/lib/cli.js:23
async function run(args) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@warriorjs/cli/bin/warriorjs.js:3:1)`

**Comment by olistic** [comment]
Hello @xeious. The warning you can ignore, it's getting fixed soon. As per the rest, there isn't enough information to go on, sorry. Please follow the issue template and try providing the data requested in it.

**Comment by glenpierce** [comment]
Running `npm install --global @warriorjs/core` solved this issue for me.

**Comment by glenpierce** [comment]
@olistic  thanks, I've created the ticket. the command for gathering my environment details failed. I've simply included my npm version (4.5.0) and node version (6.10.3) for now.

**Comment by olistic** [comment]
@xeious I'm closing this in favor of #80. If after following the resolution steps there (upgrade to Node 8) you're still having issues, please open another issue following the issue template. Thanks!
